### PR TITLE
Merge Context Error

### PR DESCRIPTION
**Pull request by LeonardJ09**
The merge context feature creates repeated start and end points, sometimes with different values. Additionally, some of the values from the merged context differ from that of the unmerged context when values were already spaced such that the merge should not have changed the methylation fractions. Look to images

merged

unmerged

### CODE REVIEW

**Comment by dpryan79** [comment]
That's odd. Would it be possible for you to post a small BAM file somewhere containing a region with just a couple of these sites? That'd help be fix the C code more quickly (though the R method that @ttriche wrote should work nicely). I'd prefer to get the C code fixed and also just provide the Rscript as an additional method that people can use.

**Comment by LeonardJ09** [comment]
So you would like the bam file that I used to produce the errors?

On Fri, Jul 17, 2015 at 1:33 AM, Devon Ryan <notifications@github.com>
wrote:

> That's odd. Would it be possible for you to post a small BAM file
> somewhere containing a region with just a couple of these sites? That'd
> help be fix the C code more quickly (though the R method that @ttriche
> <https://github.com/ttriche> wrote should work nicely). I'd prefer to get
> the C code fixed and also just provide the Rscript as an additional method
> that people can use.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dpryan79/PileOMeth/pull/15#issuecomment-122216648>.
>



-- 
Jacob Leonard
University of Southern California Class of 2015
Dana and David Dornsife College of Letters, Arts and Sciences
B.A. Applied and Computational Mathematics
Cell: (413) 461-5262
Email: leonard.jacob09@gmail.com

**Comment by ttriche** [comment]
The R method is a hack, it's not meant to go into the repo

Jacob: if you can just take the first 1000 or so lines of a BAM, that should do it

--t

**Comment by dpryan79** [comment]
We just ran into an internal file that's producing the same issue. I'm investigating the cause.

**Comment by dpryan79** [comment]
OK, I was able to track down and fix the cause of this. I think the problem was that I never personally use the `--mergeContext` option, but rather the separate `mergeContext` function, which wasn't affected by the bug. Anyway, this should be fixed as of b8bf1448294bad9ef90c5c583bce4b7231533d02.

**Pull request closed without merging**
