### PR TITLE
Devon m bias plot

### PR DESCRIPTION
**Pull request by dpryan79**
This branch implements a (somewhat) basic methylation bias plotting program and also enables PileOMeth to use inclusion/trimming bounds. I ended up just using the same syntax that's used in bison for this, since it'll cover all use cases that at least I can think of. Changes to that are certainly welcome, of course.

I should note that in the process of doing this, I found that the read pair overlap detection provided by HTSlib has some issues. It will miss any pair that overlaps but where read 2 (or 1 for that matter) has been heavily trimmed such that the fragment insert size is more than twice the shorter read's length. With BS-seq (and RRBS in particular), this isn't exactly an uncommon occurrence. I'll actually start a new branch to work on that, since I'd like to start using PileOMeth more and this problem is a deal-breaker for me.

BTW, it'd make sense to merge some of the code between "PileOMeth" and "PileOMethMbias" and then put them both in a single executable (so "PileOMeth mbias" and "PileOMeth extract" or something like that).

### CODE REVIEW

**Comment by brentp** [comment]
If you keep this up, PileOMeth is going to become extremely useful.

**Comment by dpryan79** [comment]
That's the goal :) Anyway, let me know if you have any issues with this or the other pull request I just created. If not I'll merge them.

**Comment by brentp** [comment]
I just gave it a quick read, but looks good. I like the SVG idea.

**Comment by dpryan79** [comment]
Yeah, I was trying to come up with a convenient visualization method and then I remembered Pierre Lindenbaum posting some example visualizations in SVG on twitter. It turns out that it's a pretty convenient way to do things (well, more convenient than adding a non-standard library dependence).

**Pull request merged**
